Added Mobile Responsiveness and Close Button to Chat Window
FlowiseAI/FlowiseChatEmbed pull request #183
Opened 2024-06-05 09:30 UTC by amansoni7477030

1. Added Mobile Responsiveness.
2. Slightly changed the position of the clear button.
3. Added Close Button to Chat Window at the top, following the clear button.
4. When clicking on the chatbot icon in mobile, the chat window now appears in full screen, and the chatbot icon disappears.
5. Removed auto-focus in the chat window input on mobile devices. This change improves the user experience as it prevents the mobile keyboard from obscuring the window, requiring users to repeatedly press "back" to read.
6. Improved responsiveness across all platforms, including Android, iOS, PC, tablet, ensuring consistent performance without any issues.

2024-06-05 10:47 UTC, toi500 commented
Wow, this is outstanding, a really fine piece of work here. I can't wait to see this working. 

Just to put @HenryHengZJ in context about the auto-focus issue https://github.com/FlowiseAI/FlowiseChatEmbed/issues/132#issuecomment-2142550970

2024-06-11 22:02 UTC, HenryHengZJ commented on src/components/inputs/textInput/components/TextInput.tsx
> +  // createEffect(() => {
why are we commenting out?
If its not mobile, we still need to focus on the input

2024-06-12 04:54 UTC, amansoni7477030 commented on src/components/inputs/textInput/components/TextInput.tsx
> +  // createEffect(() => {
I commented out the autofocus functionality because, based on user feedback, some users prefer not to have the input field automatically focused, regardless of the device type. This is particularly relevant on mobile devices where autofocus can interfere with user experience by bringing up the keyboard and obscuring the chat window. However, if you believe the autofocus should remain active for non-mobile devices, you can simply uncomment that part of the code.

2024-06-12 10:55 UTC, HenryHengZJ commented on src/components/inputs/textInput/components/TextInput.tsx
> +  // createEffect(() => {
added an `autoFocus` property that allows user to turn it on/off

2024-06-12 10:56 UTC, HenryHengZJ approved these changes

2024-06-12 10:58 UTC, HenryHengZJ commented on src/components/buttons/SendButton.tsx
> +        'py-2 px-12 justify-center font-semibold text-white focus:outline-none flex items-center disabled:opacity-50 disabled:cursor-not-allowed disabled:brightness-100 transition-all filter hover:br
when using full page chatbot, need to change to `px-4`, otherwise we see a big space: 
![image](https://github.com/FlowiseAI/FlowiseChatEmbed/assets/26460777/3f3acee7-8cb7-44f9-b65b-378be448423f)

2024-06-12 10:59 UTC, HenryHengZJ requested changes
Change to `px-4` when using full page chatbot

2024-06-12 11:15 UTC, toi500 commented on src/components/inputs/textInput/components/TextInput.tsx
> +  // createEffect(() => {
IMO, the `autoFocus` property for desktop apps / full page chatbot is a convenience feature that saves users time by automatically focusing on input fields, eliminating the need for a mouse click.

So very happy to have this as an option. Everybody wins.

https://github.com/FlowiseAI/FlowiseChatEmbed/assets/138339291/c62101ec-7a93-4bbf-9eba-ed57b5987948

2024-06-12 11:25 UTC, toi500 commented on src/components/inputs/textInput/components/TextInput.tsx
> +  // createEffect(() => {
@HenryHengZJ is the `autoFocus` option only applicable for non-mobile device, right?

2024-06-12 11:41 UTC, toi500 commented
@HenryHengZJ is the `autoFocus` option only applicable for non-mobile device, right?

2024-06-12 12:27 UTC, amansoni7477030 commented
> Change to `px-4` when using full page chatbot

@HenryHengZJ I have made the requested changes. Please review the updates.

2024-06-12 13:57 UTC, HenryHengZJ commented
Added changes to automatically disable focus when its in mobile mode

2024-06-12 13:57 UTC, HenryHengZJ approved these changes

2024-06-12 13:57 UTC, merged

2024-06-12 14:18 UTC, toi500 commented
@amansoni7477030 @HenryHengZJ  i really would like to thank you both for your work here.

I think we have now an amazing embedding chatbot app.

Thank you so much 🙌🏼

2024-06-12 14:30 UTC, amansoni7477030 commented
@toi500 You're welcome ! ithink there is new issue arrived now chatbot icon is not visible becuase of @HenryHengZJ new commit [update logic to detect mobile screen](https://github.com/FlowiseAI/FlowiseChatEmbed/pull/183/commits/2f7775e11eeb64c6f291b9b466e0b970494acd76)
![Screenshot from 2024-06-12 19-39-36](https://github.com/FlowiseAI/FlowiseChatEmbed/assets/65220576/37cac61f-034e-40bc-8f84-09383d8eb5e1)


can you also verify from your side @HenryHengZJ @toi500

2024-06-12 14:43 UTC, toi500 commented
@amansoni7477030 same

<img width="396" alt="image" src="https://github.com/FlowiseAI/FlowiseChatEmbed/assets/138339291/517975f1-ad91-4b2a-83ac-d05f8798b870">

2024-06-12 16:08 UTC, amansoni7477030 commented
Hii @HenryHengZJ @toi500 Chatbot icon is not visible issue has been fixed now check my latest PR #190